  
kind: pipeline
name: Drone

workspace:
  path: /drone/src

steps:
 - name: compile
   image: apon77/aosp:latest
   environment:
     bottoken:
       from_secret: bottoken
     chatid:
       from_secret: chatid
     repo1:
       from_secret: repo1
   
   commands:
      - sudo chown -R ci ./
      - sudo apt install bc
      - git clone --depth=1 $repo1 -b daisy msm8953 && cd msm8953
      - bash build.sh
      - curl -F document=@"$ZIPNAME" "https://api.telegram.org/bot$bottoken/sendDocument" -F chat_id="$chatid" -F "parse_mode=Markdown" -F caption="*✅ Build finished after $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds*"

trigger:
  branch:
  - master
  event:
  - push
